application: pushyrobot
version: 1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: chrismdp-pushy.py
- url: /assets
  static_dir: assets
- url: /config
  static_dir: config
- url: /gadgets
  static_dir: gadgets
- url: /test.*
  script: gaeunit.py
- url: /push.*
  script: pushy/receive.py
